# Aún sin definir este archivo
# spring.datasource.url=jdbc:postgresql://<host>:5432/pedidos360
# spring.datasource.username=...
# spring.datasource.password=...
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=false