spring.application.name=products
server.port=8082
spring.profiles.active=dev

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/6a3978a5-1a22-4be4-bbb8-a7c6279c471e}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_AUDIENCES:api://4d1afbc7-9d81-4ef4-a0e2-fd0ec724f8f4}

app.cors.allowed-origins=http://localhost:4200

management.endpoints.web.exposure.include=health,info